package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTipoUbicaciones generated by hbm2java
 */
@Entity
@Table(name = "tb_tipo_ubicaciones", catalog = "obusiness")
public class TbTipoUbicaciones implements java.io.Serializable {

	private int id;
	private String codigo;
	private String ubicacion;

	public TbTipoUbicaciones() {
	}

	public TbTipoUbicaciones(int id, String codigo, String ubicacion) {
		this.id = id;
		this.codigo = codigo;
		this.ubicacion = ubicacion;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CODIGO", nullable = false, length = 6)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "UBICACION", nullable = false, length = 45)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

}
