package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbFacTransacciones generated by hbm2java
 */
@Entity
@Table(name = "tb_fac_transacciones", catalog = "obusiness")
public class TbFacTransacciones implements java.io.Serializable {

	private TbFacTransaccionesId id;
	private int idCuadre;
	private Date fecha;

	public TbFacTransacciones() {
	}

	public TbFacTransacciones(TbFacTransaccionesId id, int idCuadre) {
		this.id = id;
		this.idCuadre = idCuadre;
	}

	public TbFacTransacciones(TbFacTransaccionesId id, int idCuadre, Date fecha) {
		this.id = id;
		this.idCuadre = idCuadre;
		this.fecha = fecha;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "tbTipoFormaPagosId", column = @Column(name = "TB_TIPO_FORMA_PAGOS_ID", nullable = false)) })
	public TbFacTransaccionesId getId() {
		return this.id;
	}

	public void setId(TbFacTransaccionesId id) {
		this.id = id;
	}

	@Column(name = "ID_CUADRE", nullable = false)
	public int getIdCuadre() {
		return this.idCuadre;
	}

	public void setIdCuadre(int idCuadre) {
		this.idCuadre = idCuadre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
