package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TsEmpAplicacionesId generated by hbm2java
 */
@Embeddable
public class TsEmpAplicacionesId implements java.io.Serializable {

	private int id;
	private int moduloAplicacion;
	private int idEmpresa;

	public TsEmpAplicacionesId() {
	}

	public TsEmpAplicacionesId(int id, int moduloAplicacion, int idEmpresa) {
		this.id = id;
		this.moduloAplicacion = moduloAplicacion;
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "modulo_aplicacion", nullable = false)
	public int getModuloAplicacion() {
		return this.moduloAplicacion;
	}

	public void setModuloAplicacion(int moduloAplicacion) {
		this.moduloAplicacion = moduloAplicacion;
	}

	@Column(name = "ID_EMPRESA", nullable = false)
	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TsEmpAplicacionesId))
			return false;
		TsEmpAplicacionesId castOther = (TsEmpAplicacionesId) other;

		return (this.getId() == castOther.getId()) && (this.getModuloAplicacion() == castOther.getModuloAplicacion())
				&& (this.getIdEmpresa() == castOther.getIdEmpresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getModuloAplicacion();
		result = 37 * result + this.getIdEmpresa();
		return result;
	}

}
