package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTipoOcupacion generated by hbm2java
 */
@Entity
@Table(name = "tb_tipo_ocupacion", catalog = "obusiness")
public class TbTipoOcupacion implements java.io.Serializable {

	private int tipoOcupacion;
	private String codigo;
	private String descripcion;

	public TbTipoOcupacion() {
	}

	public TbTipoOcupacion(int tipoOcupacion) {
		this.tipoOcupacion = tipoOcupacion;
	}

	public TbTipoOcupacion(int tipoOcupacion, String codigo, String descripcion) {
		this.tipoOcupacion = tipoOcupacion;
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	@Id

	@Column(name = "tipo_ocupacion", unique = true, nullable = false)
	public int getTipoOcupacion() {
		return this.tipoOcupacion;
	}

	public void setTipoOcupacion(int tipoOcupacion) {
		this.tipoOcupacion = tipoOcupacion;
	}

	@Column(name = "codigo", length = 6)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
