package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbMsPolizas generated by hbm2java
 */
@Entity
@Table(name = "tb_ms_polizas", catalog = "obusiness")
public class TbMsPolizas implements java.io.Serializable {

	private int id;
	private int idParticipacion;
	private int idRamo;

	public TbMsPolizas() {
	}

	public TbMsPolizas(int id, int idParticipacion, int idRamo) {
		this.id = id;
		this.idParticipacion = idParticipacion;
		this.idRamo = idRamo;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ID_PARTICIPACION", nullable = false)
	public int getIdParticipacion() {
		return this.idParticipacion;
	}

	public void setIdParticipacion(int idParticipacion) {
		this.idParticipacion = idParticipacion;
	}

	@Column(name = "ID_RAMO", nullable = false)
	public int getIdRamo() {
		return this.idRamo;
	}

	public void setIdRamo(int idRamo) {
		this.idRamo = idRamo;
	}

}
