package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbMsParticipaciones generated by hbm2java
 */
@Entity
@Table(name = "tb_ms_participaciones", catalog = "obusiness")
public class TbMsParticipaciones implements java.io.Serializable {

	private int id;
	private BigDecimal porcentaje;
	private int idEmpresa;
	private int idPersona;

	public TbMsParticipaciones() {
	}

	public TbMsParticipaciones(int id, int idEmpresa, int idPersona) {
		this.id = id;
		this.idEmpresa = idEmpresa;
		this.idPersona = idPersona;
	}

	public TbMsParticipaciones(int id, BigDecimal porcentaje, int idEmpresa, int idPersona) {
		this.id = id;
		this.porcentaje = porcentaje;
		this.idEmpresa = idEmpresa;
		this.idPersona = idPersona;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "PORCENTAJE", precision = 7, scale = 4)
	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	@Column(name = "ID_EMPRESA", nullable = false)
	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "ID_PERSONA", nullable = false)
	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

}
