package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPerDirecciones generated by hbm2java
 */
@Entity
@Table(name = "tb_per_direcciones", catalog = "obusiness")
public class TbPerDirecciones implements java.io.Serializable {

	private int id;
	private int idEmpresa;
	private int idPersona;
	private String direccion;
	private Integer idRegion;

	public TbPerDirecciones() {
	}

	public TbPerDirecciones(int id, int idEmpresa, int idPersona, String direccion) {
		this.id = id;
		this.idEmpresa = idEmpresa;
		this.idPersona = idPersona;
		this.direccion = direccion;
	}

	public TbPerDirecciones(int id, int idEmpresa, int idPersona, String direccion, Integer idRegion) {
		this.id = id;
		this.idEmpresa = idEmpresa;
		this.idPersona = idPersona;
		this.direccion = direccion;
		this.idRegion = idRegion;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ID_EMPRESA", nullable = false)
	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "ID_PERSONA", nullable = false)
	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	@Column(name = "DIRECCION", nullable = false, length = 100)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "ID_REGION")
	public Integer getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(Integer idRegion) {
		this.idRegion = idRegion;
	}

}
