package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TsCfgModulos generated by hbm2java
 */
@Entity
@Table(name = "ts_cfg_modulos", catalog = "obusiness")
public class TsCfgModulos implements java.io.Serializable {

	private int codigo;
	private String modulo;
	private String descripcion;
	private String observaciones;

	public TsCfgModulos() {
	}

	public TsCfgModulos(int codigo) {
		this.codigo = codigo;
	}

	public TsCfgModulos(int codigo, String modulo, String descripcion, String observaciones) {
		this.codigo = codigo;
		this.modulo = modulo;
		this.descripcion = descripcion;
		this.observaciones = observaciones;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "modulo", length = 10)
	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "observaciones", length = 1000)
	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
