package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TsCfgComponentes generated by hbm2java
 */
@Entity
@Table(name = "ts_cfg_componentes", catalog = "obusiness")
public class TsCfgComponentes implements java.io.Serializable {

	private String codigo;
	private String componente;
	private String codigoTipoComponente;
	private String descripcion;
	private String funcion;

	public TsCfgComponentes() {
	}

	public TsCfgComponentes(String codigo, String componente, String codigoTipoComponente) {
		this.codigo = codigo;
		this.componente = componente;
		this.codigoTipoComponente = codigoTipoComponente;
	}

	public TsCfgComponentes(String codigo, String componente, String codigoTipoComponente, String descripcion,
			String funcion) {
		this.codigo = codigo;
		this.componente = componente;
		this.codigoTipoComponente = codigoTipoComponente;
		this.descripcion = descripcion;
		this.funcion = funcion;
	}

	@Id

	@Column(name = "CODIGO", unique = true, nullable = false, length = 10)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "COMPONENTE", nullable = false, length = 100)
	public String getComponente() {
		return this.componente;
	}

	public void setComponente(String componente) {
		this.componente = componente;
	}

	@Column(name = "CODIGO_TIPO_COMPONENTE", nullable = false, length = 10)
	public String getCodigoTipoComponente() {
		return this.codigoTipoComponente;
	}

	public void setCodigoTipoComponente(String codigoTipoComponente) {
		this.codigoTipoComponente = codigoTipoComponente;
	}

	@Column(name = "DESCRIPCION", length = 20)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "FUNCION", length = 40)
	public String getFuncion() {
		return this.funcion;
	}

	public void setFuncion(String funcion) {
		this.funcion = funcion;
	}

}
