package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TsCfgModuloComponentes generated by hbm2java
 */
@Entity
@Table(name = "ts_cfg_modulo_componentes", catalog = "obusiness")
public class TsCfgModuloComponentes implements java.io.Serializable {

	private int id;
	private Integer codigoModulo;
	private String codigoComponente;
	private int componentePadre;
	private int orden;

	public TsCfgModuloComponentes() {
	}

	public TsCfgModuloComponentes(int id, int componentePadre, int orden) {
		this.id = id;
		this.componentePadre = componentePadre;
		this.orden = orden;
	}

	public TsCfgModuloComponentes(int id, Integer codigoModulo, String codigoComponente, int componentePadre,
			int orden) {
		this.id = id;
		this.codigoModulo = codigoModulo;
		this.codigoComponente = codigoComponente;
		this.componentePadre = componentePadre;
		this.orden = orden;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CODIGO_MODULO")
	public Integer getCodigoModulo() {
		return this.codigoModulo;
	}

	public void setCodigoModulo(Integer codigoModulo) {
		this.codigoModulo = codigoModulo;
	}

	@Column(name = "CODIGO_COMPONENTE", length = 10)
	public String getCodigoComponente() {
		return this.codigoComponente;
	}

	public void setCodigoComponente(String codigoComponente) {
		this.codigoComponente = codigoComponente;
	}

	@Column(name = "COMPONENTE_PADRE", nullable = false)
	public int getComponentePadre() {
		return this.componentePadre;
	}

	public void setComponentePadre(int componentePadre) {
		this.componentePadre = componentePadre;
	}

	@Column(name = "ORDEN", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

}
