package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbTipoMovimientos generated by hbm2java
 */
@Entity
@Table(name = "tb_tipo_movimientos", catalog = "obusiness")
public class TbTipoMovimientos implements java.io.Serializable {

	private int id;
	private String movimiento;
	private Integer operacion;

	public TbTipoMovimientos() {
	}

	public TbTipoMovimientos(int id) {
		this.id = id;
	}

	public TbTipoMovimientos(int id, String movimiento, Integer operacion) {
		this.id = id;
		this.movimiento = movimiento;
		this.operacion = operacion;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "MOVIMIENTO", length = 45)
	public String getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(String movimiento) {
		this.movimiento = movimiento;
	}

	@Column(name = "OPERACION")
	public Integer getOperacion() {
		return this.operacion;
	}

	public void setOperacion(Integer operacion) {
		this.operacion = operacion;
	}

}
