package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TsEmpRolesUsuarios generated by hbm2java
 */
@Entity
@Table(name = "ts_emp_roles_usuarios", catalog = "obusiness")
public class TsEmpRolesUsuarios implements java.io.Serializable {

	private Integer id;
	private int idRol;
	private int idUsuario;
	private int idEmpresa;

	public TsEmpRolesUsuarios() {
	}

	public TsEmpRolesUsuarios(int idRol, int idUsuario, int idEmpresa) {
		this.idRol = idRol;
		this.idUsuario = idUsuario;
		this.idEmpresa = idEmpresa;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ID_ROL", nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	@Column(name = "ID_USUARIO", nullable = false)
	public int getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_EMPRESA", nullable = false)
	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

}
