package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbFacTransaccionesId generated by hbm2java
 */
@Embeddable
public class TbFacTransaccionesId implements java.io.Serializable {

	private int id;
	private int tbTipoFormaPagosId;

	public TbFacTransaccionesId() {
	}

	public TbFacTransaccionesId(int id, int tbTipoFormaPagosId) {
		this.id = id;
		this.tbTipoFormaPagosId = tbTipoFormaPagosId;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TB_TIPO_FORMA_PAGOS_ID", nullable = false)
	public int getTbTipoFormaPagosId() {
		return this.tbTipoFormaPagosId;
	}

	public void setTbTipoFormaPagosId(int tbTipoFormaPagosId) {
		this.tbTipoFormaPagosId = tbTipoFormaPagosId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbFacTransaccionesId))
			return false;
		TbFacTransaccionesId castOther = (TbFacTransaccionesId) other;

		return (this.getId() == castOther.getId())
				&& (this.getTbTipoFormaPagosId() == castOther.getTbTipoFormaPagosId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getTbTipoFormaPagosId();
		return result;
	}

}
