package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TsCfgTipoComponentes generated by hbm2java
 */
@Entity
@Table(name = "ts_cfg_tipo_componentes", catalog = "obusiness")
public class TsCfgTipoComponentes implements java.io.Serializable {

	private String codigo;
	private String tipoComponente;

	public TsCfgTipoComponentes() {
	}

	public TsCfgTipoComponentes(String codigo) {
		this.codigo = codigo;
	}

	public TsCfgTipoComponentes(String codigo, String tipoComponente) {
		this.codigo = codigo;
		this.tipoComponente = tipoComponente;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false, length = 6)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "tipo_componente", length = 100)
	public String getTipoComponente() {
		return this.tipoComponente;
	}

	public void setTipoComponente(String tipoComponente) {
		this.tipoComponente = tipoComponente;
	}

}
