package co.com.obusiness.transacciones;

public enum AtributosConfiguracion {
    WEBCACHE_IP,
    WEBCACHE, //URL de webcache
	SERVLET_REPORTES,
	SERVLET_DESCARGA,
	RUTA_UPLOAD,
	RUTA_DOWNLOAD,
	MOSTRAR_STACK_ERROR,
	PAGINACION_MAXIMO,
	FORMATO_FECHACORTA,
	FORMATO_FECHAHORA,
	FORMATO_FECHALARGA,
	FORMATO_MONEDA,
	FORMATO_NUMERO,
	NRO_MESES_TRANSACCIONES,
	NRO_MESES_EXTRACTOS,
	WEB_AXON_ACCESS_PAGE,
	WEB_REDIRECCION,
	WEB_ACH_CTRL_EMPLEADOS,
	APPLICATION,
	FORMATO_NUMERO_DECIMAL,
	FORMATO_DECIMAL_CORTO
}