package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbSucUsuario generated by hbm2java
 */
@Entity
@Table(name = "tb_suc_usuario", catalog = "obusiness")
public class TbSucUsuario implements java.io.Serializable {

	private int id;
	private String estado;
	private int idSucursal;
	private int idEmpUsu;
	private int idEmpEmp;

	public TbSucUsuario() {
	}

	public TbSucUsuario(int id, int idSucursal, int idEmpUsu, int idEmpEmp) {
		this.id = id;
		this.idSucursal = idSucursal;
		this.idEmpUsu = idEmpUsu;
		this.idEmpEmp = idEmpEmp;
	}

	public TbSucUsuario(int id, String estado, int idSucursal, int idEmpUsu, int idEmpEmp) {
		this.id = id;
		this.estado = estado;
		this.idSucursal = idSucursal;
		this.idEmpUsu = idEmpUsu;
		this.idEmpEmp = idEmpEmp;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "ESTADO", length = 6)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "ID_SUCURSAL", nullable = false)
	public int getIdSucursal() {
		return this.idSucursal;
	}

	public void setIdSucursal(int idSucursal) {
		this.idSucursal = idSucursal;
	}

	@Column(name = "ID_EMP_USU", nullable = false)
	public int getIdEmpUsu() {
		return this.idEmpUsu;
	}

	public void setIdEmpUsu(int idEmpUsu) {
		this.idEmpUsu = idEmpUsu;
	}

	@Column(name = "ID_EMP_EMP", nullable = false)
	public int getIdEmpEmp() {
		return this.idEmpEmp;
	}

	public void setIdEmpEmp(int idEmpEmp) {
		this.idEmpEmp = idEmpEmp;
	}

}
