package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TbPerUbicacion generated by hbm2java
 */
@Entity
@Table(name = "tb_per_ubicacion", catalog = "obusiness")
public class TbPerUbicacion implements java.io.Serializable {

	private Integer id;
	private Integer idEmpresa;
	private int idPersona;
	private Integer tipoUbicacion;
	private String descripcion;

	public TbPerUbicacion() {
	}

	public TbPerUbicacion(int idPersona) {
		this.idPersona = idPersona;
	}

	public TbPerUbicacion(Integer idEmpresa, int idPersona, Integer tipoUbicacion, String descripcion) {
		this.idEmpresa = idEmpresa;
		this.idPersona = idPersona;
		this.tipoUbicacion = tipoUbicacion;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ID_EMPRESA")
	public Integer getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(Integer idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "ID_PERSONA", nullable = false)
	public int getIdPersona() {
		return this.idPersona;
	}

	public void setIdPersona(int idPersona) {
		this.idPersona = idPersona;
	}

	@Column(name = "TIPO_UBICACION")
	public Integer getTipoUbicacion() {
		return this.tipoUbicacion;
	}

	public void setTipoUbicacion(Integer tipoUbicacion) {
		this.tipoUbicacion = tipoUbicacion;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
