package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TsEmpPermisos generated by hbm2java
 */
@Entity
@Table(name = "ts_emp_permisos", catalog = "obusiness", uniqueConstraints = @UniqueConstraint(columnNames = "ID_ROL"))
public class TsEmpPermisos implements java.io.Serializable {

	private Integer id;
	private int idRol;
	private byte[] visualizar;
	private byte[] crear;
	private byte[] modificar;
	private byte[] eliminar;
	private String codigoComponente;

	public TsEmpPermisos() {
	}

	public TsEmpPermisos(int idRol, byte[] visualizar, byte[] crear, byte[] modificar, byte[] eliminar,
			String codigoComponente) {
		this.idRol = idRol;
		this.visualizar = visualizar;
		this.crear = crear;
		this.modificar = modificar;
		this.eliminar = eliminar;
		this.codigoComponente = codigoComponente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ID_ROL", unique = true, nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	@Column(name = "VISUALIZAR", nullable = false)
	public byte[] getVisualizar() {
		return this.visualizar;
	}

	public void setVisualizar(byte[] visualizar) {
		this.visualizar = visualizar;
	}

	@Column(name = "CREAR", nullable = false)
	public byte[] getCrear() {
		return this.crear;
	}

	public void setCrear(byte[] crear) {
		this.crear = crear;
	}

	@Column(name = "MODIFICAR", nullable = false)
	public byte[] getModificar() {
		return this.modificar;
	}

	public void setModificar(byte[] modificar) {
		this.modificar = modificar;
	}

	@Column(name = "ELIMINAR", nullable = false)
	public byte[] getEliminar() {
		return this.eliminar;
	}

	public void setEliminar(byte[] eliminar) {
		this.eliminar = eliminar;
	}

	@Column(name = "CODIGO_COMPONENTE", nullable = false, length = 10)
	public String getCodigoComponente() {
		return this.codigoComponente;
	}

	public void setCodigoComponente(String codigoComponente) {
		this.codigoComponente = codigoComponente;
	}

}
