package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbMsVigencias generated by hbm2java
 */
@Entity
@Table(name = "tb_ms_vigencias", catalog = "obusiness")
public class TbMsVigencias implements java.io.Serializable {

	private TbMsVigenciasId id;

	public TbMsVigencias() {
	}

	public TbMsVigencias(TbMsVigenciasId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idPoliza", column = @Column(name = "ID_POLIZA", nullable = false)),
			@AttributeOverride(name = "fechaExpedicion", column = @Column(name = "FECHA_EXPEDICION", length = 19)),
			@AttributeOverride(name = "fechaInicial", column = @Column(name = "FECHA_INICIAL", nullable = false, length = 19)),
			@AttributeOverride(name = "fechaFinal", column = @Column(name = "FECHA_FINAL", nullable = false, length = 19)),
			@AttributeOverride(name = "fechaVencimiento", column = @Column(name = "FECHA_VENCIMIENTO", length = 19)),
			@AttributeOverride(name = "idPeriodicidad", column = @Column(name = "ID_PERIODICIDAD", nullable = false)),
			@AttributeOverride(name = "idFormaPago", column = @Column(name = "ID_FORMA_PAGO", nullable = false)),
			@AttributeOverride(name = "prima", column = @Column(name = "Prima", nullable = false, precision = 10, scale = 0)) })
	public TbMsVigenciasId getId() {
		return this.id;
	}

	public void setId(TbMsVigenciasId id) {
		this.id = id;
	}

}
