package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TbPersonasId generated by hbm2java
 */
@Embeddable
public class TbPersonasId implements java.io.Serializable {

	private int idEmpresa;
	private int id;

	public TbPersonasId() {
	}

	public TbPersonasId(int idEmpresa, int id) {
		this.idEmpresa = idEmpresa;
		this.id = id;
	}

	@Column(name = "ID_EMPRESA", nullable = false)
	public int getIdEmpresa() {
		return this.idEmpresa;
	}

	public void setIdEmpresa(int idEmpresa) {
		this.idEmpresa = idEmpresa;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbPersonasId))
			return false;
		TbPersonasId castOther = (TbPersonasId) other;

		return (this.getIdEmpresa() == castOther.getIdEmpresa()) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEmpresa();
		result = 37 * result + this.getId();
		return result;
	}

}
