package co.com.obusiness.entidades;
// Generated 25/06/2016 12:08:16 PM by Hibernate Tools 4.3.4.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TbFacTranDetalles generated by hbm2java
 */
@Entity
@Table(name = "tb_fac_tran_detalles", catalog = "obusiness")
public class TbFacTranDetalles implements java.io.Serializable {

	private TbFacTranDetallesId id;

	public TbFacTranDetalles() {
	}

	public TbFacTranDetalles(TbFacTranDetallesId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)),
			@AttributeOverride(name = "idTransaccion", column = @Column(name = "ID_TRANSACCION", nullable = false)) })
	public TbFacTranDetallesId getId() {
		return this.id;
	}

	public void setId(TbFacTranDetallesId id) {
		this.id = id;
	}

}
